db.url=jdbc:mysql://localhost:3306/cineplex_db
db.user=root
db.password=9380

# Gmail SMTP Configuration for Real OTP Delivery
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=your_email@gmail.com
mail.smtp.password=your_app_password

# TMDB API Key for Real-Time Movie Integration
tmdb.api.key=8265bd1679663a7ea12ac168da84d2e8


